# Generated by Django 5.2.7 on 2025-10-23 06:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="User's full name", max_length=100)),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email address",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["email"], name="events_user_email_50f34e_idx")],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")],
                        help_text="Type of transaction: deposit or withdraw",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Transaction amount", max_digits=10
                    ),
                ),
                (
                    "timestamp",
                    models.PositiveIntegerField(
                        help_text="Unix timestamp when the event was received"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="events.user",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"], name="events_even_user_id_2c2383_idx"
                    ),
                    models.Index(
                        fields=["user", "transaction_type", "timestamp"],
                        name="events_even_user_id_f54fe5_idx",
                    ),
                ],
            },
        ),
    ]
