# Generated by Django 5.2.7 on 2025-10-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.BigIntegerField(
                help_text="Unix timestamp when the event was received (server time)", unique=True
            ),
        ),
    ]
